MangaInitiation/mangaORM_1-N_N-N/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MangaController;
use App\Http\Controllers\CollectionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('mangas',MangaController::class);
Route::resource('collections',CollectionController::class);

MangaInitiation/mangaORM_1-N_N-N/resources/views/collection.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Info sur le manga
@endsection


@section('contenu')
<div class="card mb-3" style = "max-width: 540px;">
   <div class ="row g-0">
        </div clas="col-md-8">
            <div class = "card-body">
                <h5 class="card-header-title">Titre : {{$collection->titre}}</h5>
                <p class="card-text">Prix : {{$collection->prix}}</p>
                <p>Les mangas de cette collection :</p>
                <ul>
                    @foreach($collection->mangas as $manga)
                        <li>{{$manga->titre}}</li>
                    @endforeach
                </ul>
         
            </div>
        </div>
    </div>
</div>
@endsection

MangaInitiation/mangaORM_1-N_N-N/resources/views/collections.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Tous les Mangas
@endsection


@section('contenu')

    @if(session()->has('info'))
        <div class="card text-white bg-success mb-3" style="max-width: 18rem">
            <div class="card-body">
                <p class="card-text">{{session('info')}}</p>
            </div>
        </div>
    @endif

<table class="table table-dark table-striped">

	<thead>
		
        <th>#</th>
		<th>Collection</th>
		
		<th>Prix</th>


        <th></th>
		
	</thead>
	
	
	@foreach ($collections as $collection)
		<tr>
		
            <td> {{ $collection->id }} </td>
			<td> {{ $collection->titre }} </td>
			
			<td> {{ $collection->prix}} </td>
			<td>
                <a class="btn btn-primary" href="{{route('collections.show', $collection->id)}}">
                    <button class ="btn btn-primary">voir</button>
                </a>
            </td>
        
		</tr>

	@endforeach

	
</table>
@endsection

MangaInitiation/mangaORM_1-N_N-N/resources/views/index.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Tous les Mangas
@endsection


@section('contenu')

    @if(session()->has('info'))
        <div class="card text-white bg-success mb-3" style="max-width: 18rem">
            <div class="card-body">
                <p class="card-text">{{session('info')}}</p>
            </div>
        </div>
    @endif

<table class="table table-dark table-striped">

	<thead>
		
        <th>#</th>
		<th>Titre</th>
		
		<th>Genre</th>

        <th></th>

		
	</thead>
	
	
	@foreach ($mangas as $manga)
		<tr>
		
            <td> {{ $manga ->id }} </td>
			<td> {{ $manga ->titre }} </td>
			
			<td> {{ $manga ->genre->lib_genre }} </td>
			<td>
                <a class="btn btn-primary" href="{{route('mangas.show', $manga->id)}}">
                    <button class ="btn btn-primary">voir</button>
                </a>
            </td>
        
		</tr>

	@endforeach

	
</table>
@endsection

MangaInitiation/mangaORM_1-N_N-N/resources/views/manga.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Info sur le manga
@endsection


@section('contenu')
<div class="card mb-3" style = "max-width: 540px;">
   <div class ="row g-0">
        <div class="col-md-4">
            <img src="{{asset($path)}}">
        </div>
        </div clas="col-md-8">
            <div class = "card-body">
                
                <h5 class="card-header-title">Titre : {{$manga->titre}}</h5>
                <p>Dessinateur : {{$dessinateur->nom_dessinateur.' '.$dessinateur->prenom_dessinateur}}</p>
                <p>Scenariste : {{$scenariste->nom_scenariste.' '.$scenariste->prenom_scenariste}}</p>
                <p>Genre : {{$genre->lib_genre}}</p>
                <hr>
                <p>Prix : {{$manga->prix}}</p>
         
            </div>
        </div>
    </div>
</div>
@endsection