MangaInitiation/mangaORM/routes/web.php
<?php

use App\Http\Controllers\MangaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/',[MangaController::class, 'index']);
// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::resource('mangas', MangaController::class);

Route::get('testFormulaire',[ TestFormController::class, 'getInfos']);
Route::post('testFormulaire', [TestFormController::class, 'postserInfos']);

require __DIR__.'/auth.php';

MangaInitiation/mangaORM/app/Models/Manga.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Manga extends Model
{
    use HasFactory;
    protected $table = 'mangas';
    protected $fillable = ['titre', 'nomDessinateur', 'nomScenariste', 'genre', 'prix', 'couverture'];
}

MangaInitiation/mangaORM/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

MangaInitiation/mangaORM/app/Http/Controllers/MangaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Manga;
use Illuminate\Http\Request;
use App\Http\Requests\InsertMangaRequest;
use Illuminate\Support\Facades\Redirect;

class MangaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mangas = Manga::all();
        return view('index', compact('mangas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //retourne la vue create : 
        return view('create') ;
    }

    /**
     * Store a newly created resource in storage. (Ajoute un manga)
     *
     * @param  \App\Http\Requests\InsertMangaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(InsertMangaRequest $request)
    {
        Manga::create($request->all());
        return view('confirm');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Manga  $manga
     * @return \Illuminate\Http\Response
     */
    public function show(Manga $manga)
    {
        return view('manga', compact('manga'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Manga  $manga
     * @return \Illuminate\Http\Response
     */
    public function edit(Manga $manga)
    {
        return view('edit', compact('manga'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\InsertMangaRequest  $request
     * @param  \App\Models\Manga  $manga
     * @return \Illuminate\Http\Response
     */
    public function update(InsertMangaRequest $request, Manga $manga)
    {
        $manga->update($request->all());
        return back()->with('info', 'le manga a bien été modifié dans la base de données');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Manga  $manga
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manga $manga)
    {
        $manga->delete();
        return back()->with('info', 'le manga a bien été supprimé de la base de données');
    }
}

MangaInitiation/mangaORM/app/Http/Controllers/TestFormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestFormController extends Controller
{
    //controller pour manip formulaire
    
    /**getInfo : affiche le formulaire au client (GET) */
    public function getInfos(){
        //retourné dans la vue monFormulaire.blade.php
        return view('monFormulaire');
    }

    /**postInfo : le client soumet son formulaire (POST) */
    public function postInfos(Request $request){
        //pas de vue crée après envoi formulaire, on affiche ce qui a était envoyé :
        return 'Le message saisi dans la zone de texte est : '.$request->input('message');
    }
}

MangaInitiation/mangaORM/resources/views/confirm.blade.php
@extends('layouts.layout')
@section('titrePage')
confirmation
@endsection

@section('titreItem')

@endsection


@section('contenu')
<div class="card">
    <header class="card-header">
        <h5 class="card-header-title"Nouveau Manga</h5>
    </header>
    <div class = "card-content">
        <div class="content">
            <p>Le nouveau manga a été ajouté.</p>
           
        </div>
    </div>
</div>
@endsection

MangaInitiation/mangaORM/resources/views/create.blade.php
@extends('layouts.layout')
@section('contenu')


<br>
<div class="container">
    <div class="row card text-white bg-dark">
        <h4 class="card-header">Ajouter un manga</h4>
        <div class="card-body">
            <form action="{{ route('mangas.store')}}" method="POST">
                @csrf
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('nomDessinateur') is-invalid @enderror" name="nomDessinateur" id="nomDessinateur" placeholder="Nom du dessinateur">
                    @error('nomDessinateur')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('nomScenariste') is-invalid @enderror" name="nomScenariste" id="nomScenariste" placeholder="Nom du scenariste">
                    @error('nomScenariste')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('genre') is-invalid @enderror" name="genre" id="genre" placeholder="Genre du Manga">

                    @error('genre')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('prix') is-invalid @enderror" name="prix" id="prix" placeholder="Prix du Manga">

                    @error('prix')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('titre') is-invalid @enderror" name="titre" id="titre" placeholder="Titre du manga">

                    @error('titre')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control" name="couverture" id="couverture" placeholder="Couverture">

                </div>
                <br>
                <button type="submit" class="btn btn-secondary">Envoyer !</button>
            </form>
        </div>
    </div>
</div>
@endsection

MangaInitiation/mangaORM/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

MangaInitiation/mangaORM/resources/views/edit.blade.php
@extends('layouts.layout')
@section('contenu')
@if(session()->has('info'))
<div class="card text-white bg-success mb-3" style="max-width: 18rem;">
    <div class="card-body">
        <p class="card-text">{{ session('info') }}</p>
    </div>
</div>
@endif
<br>
<div class="container">
    <div class="row card text-white bg-dark">
        <h4 class="card-header">Modifier un manga</h4>
        <div class="card-body">
            <form action="{{ route('mangas.update',$manga->id)}}" method="POST">
                @csrf
                @method('put')
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('nomDessinateur') is-invalid @enderror" name="nomDessinateur" id="nomDessinateur" value="{{ old('nomDessinateur', $manga->nomDessinateur) }}" placeholder="Nom du dessinateur">
                    @error('nomDessinateur')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('nomScenariste') is-invalid @enderror" name="nomScenariste" id="nomScenariste" value="{{ old('nomScenariste', $manga->nomScenariste) }}" placeholder="Nom du scenariste">
                    @error('nomScenariste')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('genre') is-invalid @enderror" name="genre" id="genre" value="{{ old('genre', $manga->genre) }}" placeholder="Genre du Manga">
                    @error('genre')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('prix') is-invalid @enderror" name="prix" id="prix" value="{{ old('prix', $manga->prix) }}" placeholder="Prix du Manga">
                    @error('prix')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control @error('titre') is-invalid @enderror" name="titre" id="titre" value="{{ old('titre', $manga->titre) }}" placeholder="Titre du manga">
                    @error('titre')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <br>
                <div class="form-group">

                    <input type="text" class="form-control" name="couverture" id="couverture" value="{{ old('couverture', $manga->couverture) }}" placeholder="Couverture">
                </div>
                <br>
                <button type="submit" class="btn btn-secondary">Envoyer !</button>
            </form>
        </div>
    </div>
</div>
@endsection

MangaInitiation/mangaORM/resources/views/index.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Tous les Mangas
@endsection


@section('contenu')

@if(session()->has('info'))
<div class="card text-white bg-success mb-3" style="max-width: 18rem">
    <div class="card-body">
        <p class="card-text">{{session('info')}}</p>
    </div>
</div>
@endif

<table class="table table-dark table-striped">

    <thead>

        <th>#</th>
        <th>Titre</th>

        <th>Genre</th>
       
        <th></th>
        @auth
            <th></th>
            <th>
            
                <th><a class="btn btn-sucess" href="{{route('mangas.create')}}"></a></th>
                
            </th>
        @endauth
        <!-- <th>
            <form action="{{route('mangas.create')}}">
                @csrf
                @method('DELETE')
                <button class="btn btn-success">Nouveau Manga</button>
            </form>
        </th> -->

    </thead>


    @foreach ($mangas as $manga)
    <tr>

        <td> {{ $manga ->id }} </td>
        <td> {{ $manga ->titre }} </td>

        <td> {{ $manga ->genre }} </td>
        <td>
            <a class="btn btn-primary" href="{{route('mangas.show', $manga->id)}}">
                <button class="btn btn-primary">voir</button>
            </a>
        </td>
        @auth
        <td>
            <a class="btn btn-warning" href="{{route('mangas.edit', $manga->id)}}">
                Modifier
            </a>
        </td>
        <td>
            <form action="{{route('mangas.destroy' , $manga->id)}}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Supprimer</button>
            </form>
        </td>
        @endauth
    </tr>

    @endforeach


</table>
@endsection

MangaInitiation/mangaORM/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

MangaInitiation/mangaORM/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

MangaInitiation/mangaORM/resources/views/layouts/layout.blade.php
<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="stylesheet" href="../../css/mangas.css">

    <title>
        @yield('titrePage')
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="mangas">MangaWorld</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="mangas">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.senscritique.com/bd/actualite/manga">Actualités</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.senscritique.com/bd/actualite/manga">Comics</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Voir
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="dessinateurs">Dessinateur</a></li>
                            <li><a class="dropdown-item" href="#">Scénaristes</a></li>

                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        @auth
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Bienvenu, {{Auth::user()->name}}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{{route('logout')}}" method="POST" style="display: none;" onclick="event.preventDefaut();
                                        document.getElementById('logout-form').submit();">
                                    {{__('Logout')}}
                                </a>
                                <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                        @else
                        <li>
                            <a class="nav-link active" aria-current="page" href="{{route('login')}}">Login</a>
                        </li>
                        <li>
                            <a class="nav-link active" aria-current="page" href="{{route('register')}}">Register</a>
                        </li>
                        @endauth
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <header>
        @yield('titreItem')
    </header>

    @yield('contenu')

    <footer class="footer">
        MangaWeb - copyright 3AInfo - 2021
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

</body>

</html

MangaInitiation/mangaORM/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

MangaInitiation/mangaORM/resources/views/manga.blade.php
@extends('layouts.layout')
@section('titrePage')
Liste des mangas :
@endsection

@section('titreItem')
Info sur le manga
@endsection


@section('contenu')
<div class="card">
    <header class="card-header">
        <h5 class="card-header-title">Titre : {{$manga->titre}}</h5>
    </header>
    <div class = "card-content">
        <div class="content">
            <p>Dessinateur : {{$manga->nomDessinateur}}</p>
            <p>Scenariste : {{$manga->nomScenariste}}</p>
            <p>Genre : {{$manga->genre}}</p>
            <hr>
            <p>Prix : {{$manga->prix}}</p>
        </div>
    </div>
</div>
@endsection

MangaInitiation/mangaORM/resources/views/monFormulaire.blade.php
@extends('layouts.layout')

@section('contenu')
    <form action = "{{ url('testFormulaire') }}" method = "POST">
        @csrf
        <label for="message">Entrez votre message : </label>
        <input type="text" name = "message" id = "message">
        <input type="submit" value="Envoyer !">
    </form>
@endsection